[book]
title = "Rust OS in 1000 Lines"
description = "一个用Rust语言实现的1000行代码操作系统教程"
authors = ["suxiaogang223"]
language = "zh"
src = "."

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/suxiaogang223/rust-os-in-1000-lines"
git-repository-icon = "fa fa-github"
edit-url-template = "https://github.com/suxiaogang223/rust-os-in-1000-lines/edit/main/docs/{path}"

[output.html.fold]
enable = true

[output.html.search]
enable = true
